name: Snapshot
concurrency: ci-${{ github.ref }}
on:
    workflow_dispatch:
    push:
        branches:
            - 1.*
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Setup Java
              run: |
                echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: fregante/setup-git-user@v2
            - uses: actions/cache@v3
              with:
                path: |
                    **/.gradle/caches
                    **/.gradle/repositories
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: ${{ runner.os }}-gradle-
            - uses: gradle/gradle-build-action@v2
              name: Setup Gradle
            - name: Build
              run: |
                  ./gradlew build
              env:
                  SNAPSHOT_MAVEN_URL: https://maven.lukebemish.dev/snapshots/
                  BUILD_CACHE_URL: ${{ secrets.BUILD_CACHE_URL }}
                  BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
                  BUILD_CACHE_PASSWORD: ${{ secrets.BUILD_CACHE_PASSWORD }}
            - name: Test - Fabric
              run: |
                  ./gradlew :fabric:runGametest
              env:
                  SNAPSHOT_MAVEN_URL: https://maven.lukebemish.dev/snapshots/
                  BUILD_CACHE_URL: ${{ secrets.BUILD_CACHE_URL }}
                  BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
                  BUILD_CACHE_PASSWORD: ${{ secrets.BUILD_CACHE_PASSWORD }}
            - name: Upload Test Report
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: junit-test-results
                  path: 'fabric/build/gametest/build/junit.xml'
                  retention-days: 1
            - name: Test - NeoForge
              run: |
                  ./gradlew :neoforge:runGameTestServer
              env:
                  SNAPSHOT_MAVEN_URL: https://maven.lukebemish.dev/snapshots/
                  BUILD_CACHE_URL: ${{ secrets.BUILD_CACHE_URL }}
                  BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
                  BUILD_CACHE_PASSWORD: ${{ secrets.BUILD_CACHE_PASSWORD }}
            - name: Publish
              run: |
                  ./gradlew publish
              env:
                  MAVEN_USER: github
                  MAVEN_PASSWORD: ${{ secrets.SNAPSHOT_MAVEN_PASSWORD }}
                  SNAPSHOT_MAVEN_URL: https://maven.lukebemish.dev/snapshots/
                  BUILD_CACHE_URL: ${{ secrets.BUILD_CACHE_URL }}
                  BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
                  BUILD_CACHE_PASSWORD: ${{ secrets.BUILD_CACHE_PASSWORD }}
